export const environment = {
  production: false,
  assets_folder: 'assets',
  badge_extension: '.webp',
  badges_folder: 'agents/badges',
  map_folder: 'maps',
  map_extensions: '.webp',
  floor_folder: 'floors',
  floor_extensions: '.webp',
  icon_folder: 'icons',
  icon_extension: '.svg',
  font_folder: 'fonts',
  images_folder: 'images',
  thumbs_folder: 'thumbs',
  confirmationLink: 'http://localhost:4200/confirmation/',
};
